! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Auxiliary Routines File
!
! Generated by KPP-3.1.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
!
! File                 : gckpp_Util.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Util

  USE gckpp_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! UTIL - Utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!
! InitSaveData - Opens the data file for writing
!   Parameters :
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE gckpp_Parameters

      open(10, file='gckpp.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!
! SaveData - Write LOOKAT species in the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE gckpp_Global
      USE gckpp_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
      (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
 999  FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!
! CloseSaveData - Close the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE gckpp_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!
! GenerateMatlab - Generates MATLAB file to load the data file
!   Parameters :
!                It will have a character string to prefix each
!                species name with.
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE gckpp_Parameters
      USE gckpp_Global
      USE gckpp_Monitor


      CHARACTER(LEN=8) PREFIX
      INTEGER i

      open(20, file='gckpp.m')
      write(20,*) 'load gckpp.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = gckpp;')
      write(20,*) 'clear gckpp;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do

      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! ****************************************************************
!
! Integrator_Update_Options - determine whether to call Update_RCONST,
!    Update_PHOTO, and Update_SUN from within the integrator
!
!   Parameters:
!    option (input)
!        = -1 :  Do not call Update_* functions within the integrator
!        =  0 :  Status quo: Call whichever functions are normally called
!        =  1 :  Call Update_RCONST from within the integrator
!        =  2 :  Call Update_PHOTO from within the integrator
!        =  3 :  Call Update_RCONST and Update_PHOTO from within the int.
!        =  4 :  Call Update_SUN from within the integrator
!        =  5 :  Call Update_SUN and Update_RCONST from within the int.
!        =  6 :  not implemented
!        =  7 :  not implemented
!
!    Do_Update_RCONST (output):
!        =T : Calls Update_RCONST from within the integrator
!        =F : Does not call UPDATE_RCONST from w/in the int.
!
!    Do_Update_PHOTO (output):
!        =T : Calls Update_PHOTO from within the integrator
!        =F : Does not call UPDATE_PHOTO from w/in the int.
!
!    Do_Update_SUN (output):
!        =T : Calls Update_SUN from within the integrator
!        =F : Does not call UPDATE_SUN from w/in the int.
!
! ****************************************************************

      SUBROUTINE Integrator_Update_Options( option,            &
                                            Do_Update_RConst,  &
                                            Do_Update_Photo,   &
                                            Do_Update_Sun     )

      !~~~> Input variables
      INTEGER, INTENT(IN)  :: option

      !~~~> Output variables
      LOGICAL, INTENT(OUT) :: Do_Update_RCONST
      LOGICAL, INTENT(OUT) :: Do_Update_PHOTO
      LOGICAL, INTENT(OUT) :: Do_Update_SUN

      ! Option -1: turn off all Update_* calls within the integrator
      IF ( option == -1 ) THEN
         Do_Update_RCONST = .FALSE.
         Do_Update_PHOTO  = .FALSE.
         Do_Update_SUN    = .FALSE.
         RETURN
      ENDIF

      ! Otherwise determine from the value passed
      Do_Update_RCONST = ( IAND( option, 1 ) > 0 )
      Do_Update_PHOTO  = ( IAND( option, 2 ) > 0 )
      Do_Update_SUN    = ( IAND( option, 4 ) > 0 )

      END SUBROUTINE Integrator_Update_Options

! End of Integrator_Update_Options function
! ****************************************************************
! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(245) = V_USER(1)
  V(231) = V_USER(2)
  V(227) = V_USER(3)
  V(4) = V_USER(4)
  V(272) = V_USER(5)
  V(120) = V_USER(6)
  V(5) = V_USER(7)
  V(191) = V_USER(8)
  V(165) = V_USER(9)
  V(155) = V_USER(10)
  V(260) = V_USER(11)
  V(204) = V_USER(12)
  V(265) = V_USER(13)
  V(107) = V_USER(14)
  V(71) = V_USER(15)
  V(166) = V_USER(16)
  V(199) = V_USER(17)
  V(113) = V_USER(18)
  V(286) = V_USER(19)
  V(132) = V_USER(20)
  V(141) = V_USER(21)
  V(57) = V_USER(22)
  V(185) = V_USER(23)
  V(298) = V_USER(24)
  V(13) = V_USER(25)
  V(297) = V_USER(26)
  V(281) = V_USER(27)
  V(6) = V_USER(28)
  V(188) = V_USER(29)
  V(77) = V_USER(30)
  V(103) = V_USER(31)
  V(64) = V_USER(32)
  V(82) = V_USER(33)
  V(167) = V_USER(34)
  V(129) = V_USER(35)
  V(150) = V_USER(36)
  V(151) = V_USER(37)
  V(58) = V_USER(38)
  V(59) = V_USER(39)
  V(60) = V_USER(40)
  V(61) = V_USER(41)
  V(62) = V_USER(42)
  V(63) = V_USER(43)
  V(84) = V_USER(44)
  V(85) = V_USER(45)
  V(1) = V_USER(46)
  V(2) = V_USER(47)
  V(3) = V_USER(48)
  V(271) = V_USER(49)
  V(242) = V_USER(50)
  V(105) = V_USER(51)
  V(49) = V_USER(52)
  V(202) = V_USER(53)
  V(154) = V_USER(54)
  V(52) = V_USER(55)
  V(193) = V_USER(56)
  V(78) = V_USER(57)
  V(79) = V_USER(58)
  V(294) = V_USER(59)
  V(205) = V_USER(60)
  V(83) = V_USER(61)
  V(243) = V_USER(62)
  V(270) = V_USER(63)
  V(291) = V_USER(64)
  V(114) = V_USER(65)
  V(274) = V_USER(66)
  V(7) = V_USER(67)
  V(121) = V_USER(68)
  V(181) = V_USER(69)
  V(172) = V_USER(70)
  V(137) = V_USER(71)
  V(217) = V_USER(72)
  V(76) = V_USER(73)
  V(125) = V_USER(74)
  V(102) = V_USER(75)
  V(109) = V_USER(76)
  V(187) = V_USER(77)
  V(225) = V_USER(78)
  V(116) = V_USER(79)
  V(47) = V_USER(80)
  V(244) = V_USER(81)
  V(230) = V_USER(82)
  V(184) = V_USER(83)
  V(65) = V_USER(84)
  V(53) = V_USER(85)
  V(54) = V_USER(86)
  V(288) = V_USER(87)
  V(220) = V_USER(88)
  V(258) = V_USER(89)
  V(284) = V_USER(90)
  V(201) = V_USER(91)
  V(88) = V_USER(92)
  V(89) = V_USER(93)
  V(90) = V_USER(94)
  V(91) = V_USER(95)
  V(287) = V_USER(96)
  V(219) = V_USER(97)
  V(75) = V_USER(98)
  V(92) = V_USER(99)
  V(108) = V_USER(100)
  V(93) = V_USER(101)
  V(200) = V_USER(102)
  V(273) = V_USER(103)
  V(111) = V_USER(104)
  V(296) = V_USER(105)
  V(268) = V_USER(106)
  V(279) = V_USER(107)
  V(276) = V_USER(108)
  V(139) = V_USER(109)
  V(196) = V_USER(110)
  V(128) = V_USER(111)
  V(197) = V_USER(112)
  V(124) = V_USER(113)
  V(134) = V_USER(114)
  V(135) = V_USER(115)
  V(179) = V_USER(116)
  V(66) = V_USER(117)
  V(277) = V_USER(118)
  V(148) = V_USER(119)
  V(50) = V_USER(120)
  V(55) = V_USER(121)
  V(48) = V_USER(122)
  V(80) = V_USER(123)
  V(182) = V_USER(124)
  V(203) = V_USER(125)
  V(106) = V_USER(126)
  V(248) = V_USER(127)
  V(156) = V_USER(128)
  V(214) = V_USER(129)
  V(115) = V_USER(130)
  V(133) = V_USER(131)
  V(149) = V_USER(132)
  V(241) = V_USER(133)
  V(174) = V_USER(134)
  V(175) = V_USER(135)
  V(170) = V_USER(136)
  V(251) = V_USER(137)
  V(152) = V_USER(138)
  V(140) = V_USER(139)
  V(236) = V_USER(140)
  V(136) = V_USER(141)
  V(237) = V_USER(142)
  V(122) = V_USER(143)
  V(228) = V_USER(144)
  V(147) = V_USER(145)
  V(145) = V_USER(146)
  V(222) = V_USER(147)
  V(254) = V_USER(148)
  V(255) = V_USER(149)
  V(229) = V_USER(150)
  V(195) = V_USER(151)
  V(190) = V_USER(152)
  V(192) = V_USER(153)
  V(198) = V_USER(154)
  V(131) = V_USER(155)
  V(8) = V_USER(156)
  V(67) = V_USER(157)
  V(252) = V_USER(158)
  V(253) = V_USER(159)
  V(189) = V_USER(160)
  V(162) = V_USER(161)
  V(235) = V_USER(162)
  V(104) = V_USER(163)
  V(211) = V_USER(164)
  V(278) = V_USER(165)
  V(94) = V_USER(166)
  V(9) = V_USER(167)
  V(10) = V_USER(168)
  V(232) = V_USER(169)
  V(173) = V_USER(170)
  V(157) = V_USER(171)
  V(221) = V_USER(172)
  V(250) = V_USER(173)
  V(261) = V_USER(174)
  V(11) = V_USER(175)
  V(12) = V_USER(176)
  V(177) = V_USER(177)
  V(233) = V_USER(178)
  V(14) = V_USER(179)
  V(15) = V_USER(180)
  V(16) = V_USER(181)
  V(17) = V_USER(182)
  V(20) = V_USER(183)
  V(21) = V_USER(184)
  V(24) = V_USER(185)
  V(23) = V_USER(186)
  V(25) = V_USER(187)
  V(26) = V_USER(188)
  V(259) = V_USER(189)
  V(215) = V_USER(190)
  V(142) = V_USER(191)
  V(257) = V_USER(192)
  V(95) = V_USER(193)
  V(269) = V_USER(194)
  V(138) = V_USER(195)
  V(169) = V_USER(196)
  V(207) = V_USER(197)
  V(183) = V_USER(198)
  V(238) = V_USER(199)
  V(212) = V_USER(200)
  V(146) = V_USER(201)
  V(234) = V_USER(202)
  V(96) = V_USER(203)
  V(240) = V_USER(204)
  V(275) = V_USER(205)
  V(226) = V_USER(206)
  V(51) = V_USER(207)
  V(186) = V_USER(208)
  V(208) = V_USER(209)
  V(143) = V_USER(210)
  V(158) = V_USER(211)
  V(81) = V_USER(212)
  V(28) = V_USER(213)
  V(159) = V_USER(214)
  V(160) = V_USER(215)
  V(256) = V_USER(216)
  V(123) = V_USER(217)
  V(176) = V_USER(218)
  V(194) = V_USER(219)
  V(239) = V_USER(220)
  V(249) = V_USER(221)
  V(213) = V_USER(222)
  V(161) = V_USER(223)
  V(72) = V_USER(224)
  V(68) = V_USER(225)
  V(180) = V_USER(226)
  V(19) = V_USER(227)
  V(69) = V_USER(228)
  V(70) = V_USER(229)
  V(290) = V_USER(230)
  V(285) = V_USER(231)
  V(282) = V_USER(232)
  V(218) = V_USER(233)
  V(97) = V_USER(234)
  V(18) = V_USER(235)
  V(283) = V_USER(236)
  V(280) = V_USER(237)
  V(293) = V_USER(238)
  V(117) = V_USER(241)
  V(73) = V_USER(242)
  V(299) = V_USER(243)
  V(98) = V_USER(244)
  V(224) = V_USER(245)
  V(223) = V_USER(246)
  V(247) = V_USER(247)
  V(74) = V_USER(248)
  V(126) = V_USER(249)
  V(246) = V_USER(250)
  V(127) = V_USER(251)
  V(216) = V_USER(252)
  V(118) = V_USER(253)
  V(56) = V_USER(254)
  V(209) = V_USER(255)
  V(206) = V_USER(256)
  V(266) = V_USER(257)
  V(119) = V_USER(258)
  V(110) = V_USER(259)
  V(263) = V_USER(260)
  V(210) = V_USER(261)
  V(264) = V_USER(262)
  V(99) = V_USER(263)
  V(100) = V_USER(264)
  V(101) = V_USER(265)
  V(267) = V_USER(266)
  V(262) = V_USER(267)
  V(163) = V_USER(268)
  V(168) = V_USER(269)
  V(178) = V_USER(270)
  V(171) = V_USER(271)
  V(164) = V_USER(272)
  V(112) = V_USER(273)
  V(153) = V_USER(274)
  V(144) = V_USER(275)
  V(289) = V_USER(276)
  V(292) = V_USER(277)
  V(295) = V_USER(282)
  V(130) = V_USER(283)
  V(29) = V_USER(284)
  V(30) = V_USER(285)
  V(31) = V_USER(286)
  V(86) = V_USER(287)
  V(22) = V_USER(288)
  V(87) = V_USER(289)
  V(27) = V_USER(290)
  V(32) = V_USER(291)
  V(33) = V_USER(292)
  V(34) = V_USER(293)
  V(35) = V_USER(294)
  V(36) = V_USER(295)
  V(37) = V_USER(296)
  V(38) = V_USER(297)
  V(39) = V_USER(298)

END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(245)
  V_USER(2) = V(231)
  V_USER(3) = V(227)
  V_USER(4) = V(4)
  V_USER(5) = V(272)
  V_USER(6) = V(120)
  V_USER(7) = V(5)
  V_USER(8) = V(191)
  V_USER(9) = V(165)
  V_USER(10) = V(155)
  V_USER(11) = V(260)
  V_USER(12) = V(204)
  V_USER(13) = V(265)
  V_USER(14) = V(107)
  V_USER(15) = V(71)
  V_USER(16) = V(166)
  V_USER(17) = V(199)
  V_USER(18) = V(113)
  V_USER(19) = V(286)
  V_USER(20) = V(132)
  V_USER(21) = V(141)
  V_USER(22) = V(57)
  V_USER(23) = V(185)
  V_USER(24) = V(298)
  V_USER(25) = V(13)
  V_USER(26) = V(297)
  V_USER(27) = V(281)
  V_USER(28) = V(6)
  V_USER(29) = V(188)
  V_USER(30) = V(77)
  V_USER(31) = V(103)
  V_USER(32) = V(64)
  V_USER(33) = V(82)
  V_USER(34) = V(167)
  V_USER(35) = V(129)
  V_USER(36) = V(150)
  V_USER(37) = V(151)
  V_USER(38) = V(58)
  V_USER(39) = V(59)
  V_USER(40) = V(60)
  V_USER(41) = V(61)
  V_USER(42) = V(62)
  V_USER(43) = V(63)
  V_USER(44) = V(84)
  V_USER(45) = V(85)
  V_USER(46) = V(1)
  V_USER(47) = V(2)
  V_USER(48) = V(3)
  V_USER(49) = V(271)
  V_USER(50) = V(242)
  V_USER(51) = V(105)
  V_USER(52) = V(49)
  V_USER(53) = V(202)
  V_USER(54) = V(154)
  V_USER(55) = V(52)
  V_USER(56) = V(193)
  V_USER(57) = V(78)
  V_USER(58) = V(79)
  V_USER(59) = V(294)
  V_USER(60) = V(205)
  V_USER(61) = V(83)
  V_USER(62) = V(243)
  V_USER(63) = V(270)
  V_USER(64) = V(291)
  V_USER(65) = V(114)
  V_USER(66) = V(274)
  V_USER(67) = V(7)
  V_USER(68) = V(121)
  V_USER(69) = V(181)
  V_USER(70) = V(172)
  V_USER(71) = V(137)
  V_USER(72) = V(217)
  V_USER(73) = V(76)
  V_USER(74) = V(125)
  V_USER(75) = V(102)
  V_USER(76) = V(109)
  V_USER(77) = V(187)
  V_USER(78) = V(225)
  V_USER(79) = V(116)
  V_USER(80) = V(47)
  V_USER(81) = V(244)
  V_USER(82) = V(230)
  V_USER(83) = V(184)
  V_USER(84) = V(65)
  V_USER(85) = V(53)
  V_USER(86) = V(54)
  V_USER(87) = V(288)
  V_USER(88) = V(220)
  V_USER(89) = V(258)
  V_USER(90) = V(284)
  V_USER(91) = V(201)
  V_USER(92) = V(88)
  V_USER(93) = V(89)
  V_USER(94) = V(90)
  V_USER(95) = V(91)
  V_USER(96) = V(287)
  V_USER(97) = V(219)
  V_USER(98) = V(75)
  V_USER(99) = V(92)
  V_USER(100) = V(108)
  V_USER(101) = V(93)
  V_USER(102) = V(200)
  V_USER(103) = V(273)
  V_USER(104) = V(111)
  V_USER(105) = V(296)
  V_USER(106) = V(268)
  V_USER(107) = V(279)
  V_USER(108) = V(276)
  V_USER(109) = V(139)
  V_USER(110) = V(196)
  V_USER(111) = V(128)
  V_USER(112) = V(197)
  V_USER(113) = V(124)
  V_USER(114) = V(134)
  V_USER(115) = V(135)
  V_USER(116) = V(179)
  V_USER(117) = V(66)
  V_USER(118) = V(277)
  V_USER(119) = V(148)
  V_USER(120) = V(50)
  V_USER(121) = V(55)
  V_USER(122) = V(48)
  V_USER(123) = V(80)
  V_USER(124) = V(182)
  V_USER(125) = V(203)
  V_USER(126) = V(106)
  V_USER(127) = V(248)
  V_USER(128) = V(156)
  V_USER(129) = V(214)
  V_USER(130) = V(115)
  V_USER(131) = V(133)
  V_USER(132) = V(149)
  V_USER(133) = V(241)
  V_USER(134) = V(174)
  V_USER(135) = V(175)
  V_USER(136) = V(170)
  V_USER(137) = V(251)
  V_USER(138) = V(152)
  V_USER(139) = V(140)
  V_USER(140) = V(236)
  V_USER(141) = V(136)
  V_USER(142) = V(237)
  V_USER(143) = V(122)
  V_USER(144) = V(228)
  V_USER(145) = V(147)
  V_USER(146) = V(145)
  V_USER(147) = V(222)
  V_USER(148) = V(254)
  V_USER(149) = V(255)
  V_USER(150) = V(229)
  V_USER(151) = V(195)
  V_USER(152) = V(190)
  V_USER(153) = V(192)
  V_USER(154) = V(198)
  V_USER(155) = V(131)
  V_USER(156) = V(8)
  V_USER(157) = V(67)
  V_USER(158) = V(252)
  V_USER(159) = V(253)
  V_USER(160) = V(189)
  V_USER(161) = V(162)
  V_USER(162) = V(235)
  V_USER(163) = V(104)
  V_USER(164) = V(211)
  V_USER(165) = V(278)
  V_USER(166) = V(94)
  V_USER(167) = V(9)
  V_USER(168) = V(10)
  V_USER(169) = V(232)
  V_USER(170) = V(173)
  V_USER(171) = V(157)
  V_USER(172) = V(221)
  V_USER(173) = V(250)
  V_USER(174) = V(261)
  V_USER(175) = V(11)
  V_USER(176) = V(12)
  V_USER(177) = V(177)
  V_USER(178) = V(233)
  V_USER(179) = V(14)
  V_USER(180) = V(15)
  V_USER(181) = V(16)
  V_USER(182) = V(17)
  V_USER(183) = V(20)
  V_USER(184) = V(21)
  V_USER(185) = V(24)
  V_USER(186) = V(23)
  V_USER(187) = V(25)
  V_USER(188) = V(26)
  V_USER(189) = V(259)
  V_USER(190) = V(215)
  V_USER(191) = V(142)
  V_USER(192) = V(257)
  V_USER(193) = V(95)
  V_USER(194) = V(269)
  V_USER(195) = V(138)
  V_USER(196) = V(169)
  V_USER(197) = V(207)
  V_USER(198) = V(183)
  V_USER(199) = V(238)
  V_USER(200) = V(212)
  V_USER(201) = V(146)
  V_USER(202) = V(234)
  V_USER(203) = V(96)
  V_USER(204) = V(240)
  V_USER(205) = V(275)
  V_USER(206) = V(226)
  V_USER(207) = V(51)
  V_USER(208) = V(186)
  V_USER(209) = V(208)
  V_USER(210) = V(143)
  V_USER(211) = V(158)
  V_USER(212) = V(81)
  V_USER(213) = V(28)
  V_USER(214) = V(159)
  V_USER(215) = V(160)
  V_USER(216) = V(256)
  V_USER(217) = V(123)
  V_USER(218) = V(176)
  V_USER(219) = V(194)
  V_USER(220) = V(239)
  V_USER(221) = V(249)
  V_USER(222) = V(213)
  V_USER(223) = V(161)
  V_USER(224) = V(72)
  V_USER(225) = V(68)
  V_USER(226) = V(180)
  V_USER(227) = V(19)
  V_USER(228) = V(69)
  V_USER(229) = V(70)
  V_USER(230) = V(290)
  V_USER(231) = V(285)
  V_USER(232) = V(282)
  V_USER(233) = V(218)
  V_USER(234) = V(97)
  V_USER(235) = V(18)
  V_USER(236) = V(283)
  V_USER(237) = V(280)
  V_USER(238) = V(293)
  V_USER(241) = V(117)
  V_USER(242) = V(73)
  V_USER(243) = V(299)
  V_USER(244) = V(98)
  V_USER(245) = V(224)
  V_USER(246) = V(223)
  V_USER(247) = V(247)
  V_USER(248) = V(74)
  V_USER(249) = V(126)
  V_USER(250) = V(246)
  V_USER(251) = V(127)
  V_USER(252) = V(216)
  V_USER(253) = V(118)
  V_USER(254) = V(56)
  V_USER(255) = V(209)
  V_USER(256) = V(206)
  V_USER(257) = V(266)
  V_USER(258) = V(119)
  V_USER(259) = V(110)
  V_USER(260) = V(263)
  V_USER(261) = V(210)
  V_USER(262) = V(264)
  V_USER(263) = V(99)
  V_USER(264) = V(100)
  V_USER(265) = V(101)
  V_USER(266) = V(267)
  V_USER(267) = V(262)
  V_USER(268) = V(163)
  V_USER(269) = V(168)
  V_USER(270) = V(178)
  V_USER(271) = V(171)
  V_USER(272) = V(164)
  V_USER(273) = V(112)
  V_USER(274) = V(153)
  V_USER(275) = V(144)
  V_USER(276) = V(289)
  V_USER(277) = V(292)
  V_USER(282) = V(295)
  V_USER(283) = V(130)
  V_USER(284) = V(29)
  V_USER(285) = V(30)
  V_USER(286) = V(31)
  V_USER(287) = V(86)
  V_USER(288) = V(22)
  V_USER(289) = V(87)
  V_USER(290) = V(27)
  V_USER(291) = V(32)
  V_USER(292) = V(33)
  V_USER(293) = V(34)
  V_USER(294) = V(35)
  V_USER(295) = V(36)
  V_USER(296) = V(37)
  V_USER(297) = V(38)
  V_USER(298) = V(39)

END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)


END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! Get_OHreactivity - returns the OH reactivity
! The OH reactivity is defined as the inverse of its lifetime.
! This routine was auto-generated using script OHreact_parser.py.
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Get_OHreactivity ( CC, RR, OHreact )

! CC - Concentrations of species (local)
  REAL(kind=dp) :: CC(NSPEC)
! RR - reaction rates (local)
  REAL(kind=dp) :: RR(NREACT)
! OHreact - OH reactivity [s-1]
  REAL(kind=dp) :: OHreact

  OHreact = RR(12)*CC(93) + RR(14)*CC(293) + 2*RR(18) + 2*RR(19) + RR(20)*CC(296) &
          + RR(21)*CC(220) + RR(24)*CC(274) + RR(25)*CC(193) + RR(31)*CC(275) + RR(32)*CC(143) &
          + RR(33)*CC(204) + RR(34)*CC(271) + RR(35)*CC(285) + RR(36)*CC(273) + RR(37)*CC(290) &
          + RR(38)*CC(200) + RR(41)*CC(111) + RR(44)*CC(282) + RR(47)*CC(219) + RR(48)*CC(226) &
          + RR(51)*CC(272) + RR(56)*CC(167) + RR(60)*CC(129) + RR(61)*CC(129) + RR(65)*CC(120) &
          + RR(75)*CC(210) + RR(76)*CC(227) + RR(77)*CC(267) + RR(82)*CC(231) + RR(91)*CC(234) &
          + RR(101)*CC(137) + RR(102)*CC(164) + RR(110)*CC(266) + RR(112)*CC(244) + RR(113)*CC(244) &
          + RR(115)*CC(230) + RR(116)*CC(240) + RR(119)*CC(258) + RR(120)*CC(258) + RR(121)*CC(119) &
          + RR(122)*CC(116) + RR(123)*CC(100) + RR(124)*CC(101) + RR(125)*CC(99) + RR(126)*CC(112) &
          + RR(127)*CC(118) + RR(128)*CC(24) + RR(129)*CC(95) + RR(148)*CC(181) + RR(149)*CC(181) &
          + RR(158)*CC(66) + RR(160)*CC(295) + RR(164)*CC(284) + RR(169)*CC(132) + RR(172)*CC(298) &
          + RR(181)*CC(78) + RR(182)*CC(84) + RR(183)*CC(105) + RR(192)*CC(300) + RR(193)*CC(283) &
          + RR(197)*CC(73) + RR(231)*CC(205) + RR(233)*CC(291) + RR(234)*CC(291) + RR(235)*CC(117) &
          + RR(236)*CC(83) + RR(237)*CC(287) + RR(238)*CC(279) + RR(239)*CC(243) + RR(240)*CC(270) &
          + RR(241)*CC(154) + RR(242)*CC(85) + RR(243)*CC(79) + RR(244)*CC(49) + RR(245)*CC(91) &
          + RR(246)*CC(89) + RR(247)*CC(90) + RR(248)*CC(88) + RR(310)*CC(148) + RR(311)*CC(75) &
          + RR(312)*CC(276) + RR(317)*CC(52) + RR(318)*CC(217) + RR(319)*CC(206) + RR(333)*CC(159) &
          + RR(334)*CC(160) + RR(344)*CC(177) + RR(352)*CC(127) + RR(366)*CC(186) + RR(367)*CC(208) &
          + RR(373)*CC(139) + RR(374)*CC(96) + RR(375)*CC(102) + RR(376)*CC(94) + RR(377)*CC(97) &
          + RR(379)*CC(232) + RR(380)*CC(232) + RR(381)*CC(232) + RR(382)*CC(232) + RR(409)*CC(196) &
          + RR(410)*CC(197) + RR(411)*CC(134) + RR(412)*CC(135) + RR(413)*CC(201) + RR(414)*CC(182) &
          + RR(415)*CC(115) + RR(416)*CC(163) + RR(417)*CC(163) + RR(418)*CC(168) + RR(419)*CC(168) &
          + RR(420)*CC(163) + RR(421)*CC(168) + RR(422)*CC(178) + RR(423)*CC(171) + RR(436)*CC(122) &
          + RR(437)*CC(140) + RR(438)*CC(140) + RR(439)*CC(136) + RR(440)*CC(136) + RR(459)*CC(147) &
          + RR(460)*CC(147) + RR(461)*CC(145) + RR(462)*CC(145) + RR(463)*CC(228) + RR(464)*CC(228) &
          + RR(465)*CC(222) + RR(466)*CC(222) + RR(467)*CC(228) + RR(468)*CC(222) + RR(506)*CC(189) &
          + RR(507)*CC(162) + RR(508)*CC(189) + RR(509)*CC(162) + RR(510)*CC(162) + RR(511)*CC(189) &
          + RR(512)*CC(162) + RR(513)*CC(162) + RR(522)*CC(248) + RR(523)*CC(248) + RR(526)*CC(251) &
          + RR(529)*CC(256) + RR(531)*CC(259) + RR(532)*CC(259) + RR(535)*CC(249) + RR(536)*CC(239) &
          + RR(537)*CC(238) + RR(538)*CC(207) + RR(539)*CC(183) + RR(546)*CC(169) + RR(547)*CC(161) &
          + RR(548)*CC(123) + RR(549)*CC(194) + RR(550)*CC(176) + RR(551)*CC(138) + RR(557)*CC(142) &
          + RR(569)*CC(158) + RR(570)*CC(108) + RR(571)*CC(214) + RR(572)*CC(133) + RR(573)*CC(149) &
          + RR(574)*CC(170) + RR(575)*CC(221) + RR(576)*CC(250) + RR(578)*CC(110) + RR(579)*CC(92) &
          + RR(581)*CC(179) + RR(582)*CC(179) + RR(583)*CC(19) + RR(587)*CC(82) + RR(588)*CC(64) &
          + RR(595)*CC(76) + RR(596)*CC(125) + RR(597)*CC(125) + RR(598)*CC(71) + RR(599)*CC(86) &
          + RR(600)*CC(87) + RR(606)*CC(126) + RR(608)*CC(121) + RR(610)*CC(146) + RR(613)*CC(107) &
          + RR(618)*CC(77) + RR(620)*CC(103) + RR(625)*CC(113) + RR(628)*CC(218) + RR(632)*CC(165) &
          + RR(635)*CC(155) + RR(645)*CC(47) + RR(656)*CC(289) + RR(657)*CC(292)

END SUBROUTINE Get_OHreactivity
! End of Get_OHreactivity subroutine
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

END MODULE gckpp_Util
